### PR TITLE
fix: cache now clears upon canvas unlock

### LINKED ISSUE #408: Backend serves static locked cache if canvas unlocked
In the case that:
1. A canvas starts unlocked
2. The canvas gets locked
3. The backend saves the locked snapshot in the static cache, as intended
4. Further queries to the backend will serve the cached content rather than a new query
5. The canvas then gets unlocked (for whatever reason)
6. The backend continues to serve the static cached content instead of fetching new data

### PR DESCRIPTION
**Pull request by Rocked03**
Fixes #408

Backend keeps fetching from static locked cache even if canvas gets unlocked

### CODE REVIEW

File: packages/backend/src/services/canvasService.ts [hunk 1]
```diff
@@ -295,7 +289,16 @@ function saveCanvasToFileSystem(canvas: canvas, pixels: PixelColor[]): string {
   return path;
 }
 
-async function getAndCacheCanvas(canvasId: number): Promise<CachedCanvas> {
+function clearCanvasFromFileSystem(canvasId: number): void {
+  const cachedCanvas = CANVAS_CACHE[canvasId];
+
+  if (cachedCanvas?.isLocked) {
+    fs.rmSync(cachedCanvas.canvasPath);
```
Comment (jaskfla) [inline packages/backend/src/services/canvasService.ts]: Can `clearCanvasFromFileSystem` be async? Better to go with `fs.rm()` I reckon

File: packages/backend/src/services/canvasService.ts [hunk 2]
```diff
@@ -304,6 +307,21 @@ async function getAndCacheCanvas(canvasId: number): Promise<CachedCanvas> {
     throw new NotFoundError(`There is no canvas with ID ${canvasId}`);
   }
 
+  var cachedCanvas = CANVAS_CACHE[canvasId];
```
Comment (jaskfla) [inline packages/backend/src/services/canvasService.ts]: `var`?? Looks like this can be a `const`

File: packages/backend/src/services/canvasService.ts [hunk 3]
```diff
@@ -304,6 +307,21 @@ async function getAndCacheCanvas(canvasId: number): Promise<CachedCanvas> {
...
+  if (cachedCanvas) {
+    if (cachedCanvas.isLocked !== canvas.locked) {
+      console.debug(
+        `Canvas ${canvasId} lock status has changed. Updating cache...`,
+      );
+      clearCanvasFromFileSystem(canvasId);
+    } else {
+      console.debug(`Cache hit for canvas ${canvasId}`);
+      return CANVAS_CACHE[canvasId];
```
Comment (jaskfla) [inline packages/backend/src/services/canvasService.ts]: May as well use `cachedCanvas` reference here

**Review by jaskfla — APPROVED** [review]
