### PR TITLE
fix(types): runtime code in types package

### LINKED ISSUE #437: Cannot find module `...\packages\types\src\frame' imported from  ...\packages\types\src\index.ts`
```ps
PS C:\Users\Sam\Documents\Repositories\Canvas-Web> pnpm --filter @blurple-canvas-web/backend start

> @blurple-canvas-web/backend@0.1.0 start C:\Users\Sam\Documents\Repositories\Canvas-Web\packages\backend
> node build/index.js

⟐ injecting env (18) from .env · dotenvx@1.61.0
node:internal/modules/esm/resolve:999
    throw error;
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\Sam\Documents\Repositories\Canvas-Web\packages\types\src\frame' imported from C:\Users\Sam\Documents\Repositories\Canvas-Web\packages\types\src\index.ts
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:801:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:725:25)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:760:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:783:52)
    at #cachedResolveSync (node:internal/modules/esm/loader:744:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:462:50)
    at #link (node:internal/modules/esm/module_job:440:34) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/Sam/Documents/Repositories/Canvas-Web/packages/types/src/frame'
}

Node.js v24.4.0
C:\Users\Sam\Documents\Repositories\Canvas-Web\packages\backend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @blurple-canvas-web/backend@0.1.0 start: `node build/index.js`
Exit status 1
```

### PR DESCRIPTION
**Pull request by jaskfla**
Fixes #437

### CODE REVIEW

File: packages/backend/src/services/frameService.ts [hunk 1]
```diff
@@ -91,14 +90,14 @@ function frameFromDb(frame: FrameDbRecord): Frame {
...
-  if (frame.owner.type !== FrameOwnerType.User) {
+function assertIsUserFrame(frame: Frame): asserts frame is UserOwnedFrame {
+  if (frame.owner.type !== "user") {
     throw new Error(`Expected user-owned frame, got ${frame.owner.type}`);
   }
 }
 
-function asGuildFrame(frame: Frame): asserts frame is GuildOwnedFrame {
-  if (frame.owner.type !== FrameOwnerType.Guild) {
+function assertIsGuildFrame(frame: Frame): asserts frame is GuildOwnedFrame {
```
Comment (Rocked03) [inline packages/backend/src/services/frameService.ts]: these functions and names are already getting modified in #377, can we keep the changes in this PR minimal please?

**Review by Rocked03 — APPROVED** [review]
thanks, just the one note -- kinda want to avoid the inevitable merge conflict but it's also a bit fruitless changing the function here when it's already getting attention over in the edit frame PR

File: packages/backend/src/services/frameService.ts (hunk 1 above)
Comment (jaskfla) [reply packages/backend/src/services/frameService.ts]: e52e4f8c65c439db8333a097d9620e6426f1f6a3
